import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/nav";
import AuthProvider from "@/context/auth_context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
  <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
    <body
      style={{
        margin: 0,
        background: "#121212",
        color: "white",
        minHeight: "100vh",
        fontFamily: "'Poppins', Arial, sans-serif",
      }}
    >
      <AuthProvider>
        {/* Website Logo */}
        <header
          style={{
            padding: "25px 20px 15px",
            textAlign: "center",
            borderBottom: "1px solid #2c2c2c",
            background: "#181818",
          }}
        >
          <h1
            style={{
              margin: 0,
              fontSize: "3.5rem",
              fontWeight: "800",
              letterSpacing: "3px",
              textTransform: "uppercase",
              color: "white",
            }}
          >
            Entertainment{" "}
            <span style={{ color: "#e50914" }}>24</span>/
            <span style={{ color: "#2196f3" }}>7</span>
          </h1>

          <p
            style={{
              marginTop: "10px",
              color: "#bdbdbd",
              fontSize: "1rem",
              letterSpacing: "1px",
            }}
          >
            Entertainment Never Stops
          </p>
        </header>

        {/* Navigation */}
        <Navbar />

        {/* Main Content */}
        <main
          style={{
            maxWidth: "1700px",
            margin: "40px auto",
            padding: "0 25px",
          }}
        >
          {children}
        </main>
      </AuthProvider>
    </body>
  </html>
);
}
